INSERT INTO products.category(id, nome)
VALUES(1, 'Norte')
INSERT INTO products.category(id, nome)
VALUES(2, 'Sul')
INSERT INTO products.category(id, nome)
VALUES(3, 'Suldeste')
INSERT INTO products.category(id, nome)
VALUES(4, 'Centro-Oeste')
INSERT INTO products.category(id, nome)
VALUES(5, 'Nordeste')